--drop table IF EXISTS film_genre;
--
--drop table IF EXISTS  genres;
--
--drop table  IF EXISTS movie_likes;
--
--drop table  IF EXISTS films;
--
----drop table  IF EXISTS mpa;
--
--drop table IF EXISTS friendship;
--
--drop table  IF EXISTS users;

create table IF NOT EXISTS mpa
(
    mpa_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mpa_name varchar(5),
    CONSTRAINT mpa_id_pk PRIMARY KEY (mpa_id)
);

create table IF NOT EXISTS films
(
    film_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_title varchar(100) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration int NOT NULL,
    mpa_id int REFERENCES mpa(mpa_id),
    CONSTRAINT film_id_pk PRIMARY KEY (film_id)
);

create table IF NOT EXISTS users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(255),
    login varchar(255),
    email varchar(255) NOT NULL,
    birthday date NOT NULL,
    CONSTRAINT user_id PRIMARY KEY (user_id)
);

create table IF NOT EXISTS genres
(
    genre_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    genre_name varchar(50) NOT NULL,
    CONSTRAINT genre_id_pk PRIMARY KEY (genre_id)
);

create table IF NOT EXISTS film_genre
(
    film_id bigint NOT NULL REFERENCES films (film_id) ON delete CASCADE,
    genre_id int NOT NULL REFERENCES genres (genre_id),
    CONSTRAINT film_genre_pk PRIMARY KEY (film_id, genre_id)
);

create table IF NOT EXISTS movie_likes
(
    film_id bigint NOT NULL REFERENCES films (film_id) ON delete CASCADE,
    user_id bigint NOT NULL REFERENCES users (user_id) ON delete CASCADE,
    CONSTRAINT movie_likes_pk PRIMARY KEY (film_id, user_id)
);

create table IF NOT EXISTS friendship
(
    user_id_who_sent_request bigint NOT NULL REFERENCES users (user_id) ON delete CASCADE,
    user_id_whom_request_was_sent bigint NOT NULL REFERENCES users (user_id) ON delete CASCADE,
    CONSTRAINT friendship_pk PRIMARY KEY (user_id_who_sent_request, user_id_whom_request_was_sent)
);